aws:
  region: us-east-2

schema:
  registry:
    name: glue

bootstrap:
  url: boot-xxxxxxx.kafka-serverless.aws-region.amazonaws.com:9098

topic:
    simple:
      name:  msk-serverless-tutorial-topic-simple
      group: msk-serverless-tutorial-group-simple
    bookclub:
      name: msk-serverless-tutorial-topic-bookclub
      group: msk-serverless-tutorial-group-bookclub
      registry: msk-serverless-tutorial-registry
      schema: msk-serverless-tutorial-bookclub-schema
